apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::081153154303:user/deploy-ci
      username: deploy-ci
      groups:
        - system:masters